services:
  - type: web
    name: nail-fpt-server
    env: node
    buildCommand: npm install && npm run build && npm run migrate
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: "file:./prisma/dev.db"
      - key: JWT_SECRET
        value: "your-super-secret-key-here"
    disk:
      name: sqlite-data
      mountPath: /opt/render/project/src/prisma
      sizeGB: 1 